### ISSUE TITLE
WebTAK sources

### ISSUE THREAD

**Issue by rick51231** [TAK-Product-Center/Server#23]
As I see, there is no information about the WebTAK sources or even the compiled bundle. 
Where can I find it? 
For now, it can be obtained only from the `takserver-xxx-RELEASE-yyy.zip` archive.

**Comment by mighty-swede** [comment]
As far as I know WebTak is not released open soruce. I have PR to update doc. accordingly.
WebTAK. WebTAK is a web interface client for TAK. WebTAK has not been Not publicly released. Created by Draper. However, it is available for License from the Air Force via [TechLink].
https://wiki.civtak.org/index.php?title=TAK_Products

**Comment by takdeveloper** [comment]
Confirming that WebTAK is not open source. There is no intention to include the source code for the application with the TAK Server open source distribution at this time.
