### ISSUE TITLE
How download Map

### ISSUE THREAD

**Issue by lixunxun-skyfend** [TAK-Product-Center/Server#26]
Excuse me, where can I download the map package? I don't want my application to open as a blurry sphere. If possible, please reply to the URL below. Thank you very much!

**Comment by mighty-swede** [comment]
I suggest you explore the forums that exist for TAK. For example this
https://discord.com/channels/698067185515495436/725550034770198588

**Comment by lixunxun-skyfend** [comment]
> I suggest you explore the forums that exist for TAK. For example this https://discord.com/channels/698067185515495436/725550034770198588

Thank you very much, I have found Joshua Fuller, thank you for your help!

**Comment by lixunxun-skyfend** [comment]
> I suggest you explore the forums that exist for TAK. For example this https://discord.com/channels/698067185515495436/725550034770198588

Oh my God! I seem to have had an accident entering the forum. Could you please pull me into it? Thank you very much. My discord is 'lixun#3476' and you can search for me. Thank you again my friend!

**Comment by lixunxun-skyfend** [comment]
> I suggest you explore the forums that exist for TAK. For example this https://discord.com/channels/698067185515495436/725550034770198588

Because to your help, I have understood. Thank you very much!

**Comment by takdeveloper** [comment]
Closing based on comments.
